# Generated by Django 3.1.1 on 2020-09-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_auto_20200911_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
