# Generated by Django 3.1.1 on 2020-09-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_auto_20200919_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Empty'),
        ),
    ]
