# Generated by Django 3.1.1 on 2020-10-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='lastname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
